#title:
#email:
#description:
#url: ""
#github_username: bohadi

markdown: kramdown
theme: #minima
#plugins:

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
