title: bohadi.github.io
description:

markdown: kramdown
#theme: minima
plugins:
  - jekyll-redirect-from

github_username: bohadi
  #google_analytics: UA-106946514-1

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
